leesite-module/src/main/java/com/funtl/leesite/modules/aliyun/entity/ConfigAliyunOss.java
/*
 * Copyright 2015-2017 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.funtl.leesite.modules.aliyun.entity;

import org.hibernate.validator.constraints.Length;

import com.funtl.leesite.common.persistence.DataEntity;
import com.funtl.leesite.common.utils.excel.annotation.ExcelField;

/**
 * 阿里云配置Entity
 * @author Lusifer
 * @version 2017-05-28
 */
public class ConfigAliyunOss extends DataEntity<ConfigAliyunOss> {
	
	private static final long serialVersionUID = 1L;
	private String ossKey;		// Key
	private String ossSecret;		// Secret
	private String bucketName;		// Bucket Name
	private String ossEndPoint;		// OSS End Point
	private String autoCreateBucket;		// 自动创建 Bucket
	private String baiduUseStatus;		// 支持百度富文本
	private String useCdn;		// 启用 CDN
	private String cdnEndPoint;		// CDN End Point
	
	public ConfigAliyunOss() {
		super();
	}

	public ConfigAliyunOss(String id){
		super(id);
	}

	@Length(min=0, max=64, message="Key长度必须介于 0 和 64 之间")
	@ExcelField(title="Key", align=2, sort=1)
	public String getOssKey() {
		return ossKey;
	}

	public void setOssKey(String ossKey) {
		this.ossKey = ossKey;
	}
	
	@Length(min=0, max=64, message="Secret长度必须介于 0 和 64 之间")
	@ExcelField(title="Secret", align=2, sort=2)
	public String getOssSecret() {
		return ossSecret;
	}

	public void setOssSecret(String ossSecret) {
		this.ossSecret = ossSecret;
	}
	
	@Length(min=0, max=100, message="Bucket Name长度必须介于 0 和 100 之间")
	@ExcelField(title="Bucket Name", align=2, sort=3)
	public String getBucketName() {
		return bucketName;
	}

	public void setBucketName(String bucketName) {
		this.bucketName = bucketName;
	}
	
	@Length(min=0, max=100, message="OSS End Point长度必须介于 0 和 100 之间")
	@ExcelField(title="OSS End Point", align=2, sort=4)
	public String getOssEndPoint() {
		return ossEndPoint;
	}

	public void setOssEndPoint(String ossEndPoint) {
		this.ossEndPoint = ossEndPoint;
	}
	
	@Length(min=0, max=2, message="自动创建 Bucket长度必须介于 0 和 2 之间")
	@ExcelField(title="自动创建 Bucket", dictType="yes_no", align=2, sort=5)
	public String getAutoCreateBucket() {
		return autoCreateBucket;
	}

	public void setAutoCreateBucket(String autoCreateBucket) {
		this.autoCreateBucket = autoCreateBucket;
	}
	
	@Length(min=0, max=2, message="支持百度富文本长度必须介于 0 和 2 之间")
	@ExcelField(title="支持百度富文本", dictType="yes_no", align=2, sort=6)
	public String getBaiduUseStatus() {
		return baiduUseStatus;
	}

	public void setBaiduUseStatus(String baiduUseStatus) {
		this.baiduUseStatus = baiduUseStatus;
	}
	
	@Length(min=0, max=2, message="启用 CDN长度必须介于 0 和 2 之间")
	@ExcelField(title="启用 CDN", dictType="yes_no", align=2, sort=7)
	public String getUseCdn() {
		return useCdn;
	}

	public void setUseCdn(String useCdn) {
		this.useCdn = useCdn;
	}
	
	@Length(min=0, max=100, message="CDN End Point长度必须介于 0 和 100 之间")
	@ExcelField(title="CDN End Point", align=2, sort=8)
	public String getCdnEndPoint() {
		return cdnEndPoint;
	}

	public void setCdnEndPoint(String cdnEndPoint) {
		this.cdnEndPoint = cdnEndPoint;
	}
	
}

leesite-module/src/main/java/com/funtl/leesite/modules/aliyun/entity/ConfigAliyunPush.java
/*
 * Copyright 2015-2017 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.funtl.leesite.modules.aliyun.entity;

import com.funtl.leesite.common.persistence.DataEntity;
import com.funtl.leesite.common.utils.excel.annotation.ExcelField;

import org.hibernate.validator.constraints.Length;

/**
 * 阿里云配置Entity
 *
 * @author Lusifer
 * @version 2017-09-23
 */
public class ConfigAliyunPush extends DataEntity<ConfigAliyunPush> {

	private static final long serialVersionUID = 1L;
	private String accessKeyId;        // Key
	private String accessKeySecret;        // Secret
	private String appKey;        // AppKey
	private String regionId;        // RegionId

	public ConfigAliyunPush() {
		super();
	}

	public ConfigAliyunPush(String id) {
		super(id);
	}

	@Length(min = 0, max = 64, message = "Key长度必须介于 0 和 64 之间")
	@ExcelField(title = "Key", align = 2, sort = 1)
	public String getAccessKeyId() {
		return accessKeyId;
	}

	public void setAccessKeyId(String accessKeyId) {
		this.accessKeyId = accessKeyId;
	}

	@Length(min = 0, max = 64, message = "Secret长度必须介于 0 和 64 之间")
	@ExcelField(title = "Secret", align = 2, sort = 2)
	public String getAccessKeySecret() {
		return accessKeySecret;
	}

	public void setAccessKeySecret(String accessKeySecret) {
		this.accessKeySecret = accessKeySecret;
	}

	@Length(min = 0, max = 64, message = "AppKey长度必须介于 0 和 64 之间")
	@ExcelField(title = "AppKey", align = 2, sort = 3)
	public String getAppKey() {
		return appKey;
	}

	public void setAppKey(String appKey) {
		this.appKey = appKey;
	}

	@Length(min = 0, max = 64, message = "RegionId长度必须介于 0 和 64 之间")
	@ExcelField(title = "RegionId", align = 2, sort = 4)
	public String getRegionId() {
		return regionId;
	}

	public void setRegionId(String regionId) {
		this.regionId = regionId;
	}

}

leesite-module/src/main/java/com/funtl/leesite/modules/cases/entity/CaseOneToManyFirst.java
/*
 * Copyright 2015-2017 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.funtl.leesite.modules.cases.entity;

import org.hibernate.validator.constraints.Length;
import javax.validation.constraints.NotNull;

import com.funtl.leesite.common.persistence.DataEntity;
import com.funtl.leesite.common.utils.excel.annotation.ExcelField;

/**
 * 生成示例Entity
 * @author Lusifer
 * @version 2017-05-05
 */
public class CaseOneToManyFirst extends DataEntity<CaseOneToManyFirst> {
	
	private static final long serialVersionUID = 1L;
	private String startarea;		// 出发地
	private String endarea;		// 目的地
	private Double price;		// 代理价格
	private CaseOneToManyMain caseOneToManyMain;		// 外键 父类
	
	public CaseOneToManyFirst() {
		super();
	}

	public CaseOneToManyFirst(String id){
		super(id);
	}

	public CaseOneToManyFirst(CaseOneToManyMain caseOneToManyMain){
		this.caseOneToManyMain = caseOneToManyMain;
	}

	@Length(min=1, max=64, message="出发地长度必须介于 1 和 64 之间")
	@ExcelField(title="出发地", align=2, sort=1)
	public String getStartarea() {
		return startarea;
	}

	public void setStartarea(String startarea) {
		this.startarea = startarea;
	}
	
	@Length(min=1, max=64, message="目的地长度必须介于 1 和 64 之间")
	@ExcelField(title="目的地", align=2, sort=2)
	public String getEndarea() {
		return endarea;
	}

	public void setEndarea(String endarea) {
		this.endarea = endarea;
	}
	
	@NotNull(message="代理价格不能为空")
	@ExcelField(title="代理价格", align=2, sort=3)
	public Double getPrice() {
		return price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}
	
	@Length(min=1, max=64, message="外键长度必须介于 1 和 64 之间")
	public CaseOneToManyMain getCaseOneToManyMain() {
		return caseOneToManyMain;
	}

	public void setCaseOneToManyMain(CaseOneToManyMain caseOneToManyMain) {
		this.caseOneToManyMain = caseOneToManyMain;
	}
	
}

leesite-module/src/main/java/com/funtl/leesite/modules/cases/entity/CaseOneToManyMain.java
/*
 * Copyright 2015-2017 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.funtl.leesite.modules.cases.entity;

import com.funtl.leesite.modules.sys.entity.User;
import javax.validation.constraints.NotNull;
import com.funtl.leesite.modules.sys.entity.Office;
import com.funtl.leesite.modules.sys.entity.Area;
import org.hibernate.validator.constraints.Length;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonFormat;
import java.util.List;
import com.google.common.collect.Lists;

import com.funtl.leesite.common.persistence.DataEntity;
import com.funtl.leesite.common.utils.excel.annotation.ExcelField;

/**
 * 生成示例Entity
 * @author Lusifer
 * @version 2017-05-05
 */
public class CaseOneToManyMain extends DataEntity<CaseOneToManyMain> {
	
	private static final long serialVersionUID = 1L;
	private User user;		// 归属用户
	private Office office;		// 归属部门
	private Area area;		// 归属区域
	private String name;		// 名称
	private String sex;		// 性别
	private Date inDate;		// 加入日期
	private Date beginInDate;		// 开始 加入日期
	private Date endInDate;		// 结束 加入日期
	private List<CaseOneToManyFirst> caseOneToManyFirstList = Lists.newArrayList();		// 子表列表
	private List<CaseOneToManySecond> caseOneToManySecondList = Lists.newArrayList();		// 子表列表
	private List<CaseOneToManyThird> caseOneToManyThirdList = Lists.newArrayList();		// 子表列表
	
	public CaseOneToManyMain() {
		super();
	}

	public CaseOneToManyMain(String id){
		super(id);
	}

	@NotNull(message="归属用户不能为空")
	@ExcelField(title="归属用户", fieldType=User.class, value="user.name", align=2, sort=1)
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}
	
	@NotNull(message="归属部门不能为空")
	@ExcelField(title="归属部门", fieldType=Office.class, value="office.name", align=2, sort=2)
	public Office getOffice() {
		return office;
	}

	public void setOffice(Office office) {
		this.office = office;
	}
	
	@NotNull(message="归属区域不能为空")
	@ExcelField(title="归属区域", fieldType=Area.class, value="area.name", align=2, sort=3)
	public Area getArea() {
		return area;
	}

	public void setArea(Area area) {
		this.area = area;
	}
	
	@Length(min=1, max=100, message="名称长度必须介于 1 和 100 之间")
	@ExcelField(title="名称", align=2, sort=4)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Length(min=1, max=1, message="性别长度必须介于 1 和 1 之间")
	@ExcelField(title="性别", dictType="sex", align=2, sort=5)
	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}
	
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@NotNull(message="加入日期不能为空")
	@ExcelField(title="加入日期", align=2, sort=6)
	public Date getInDate() {
		return inDate;
	}

	public void setInDate(Date inDate) {
		this.inDate = inDate;
	}
	
	public Date getBeginInDate() {
		return beginInDate;
	}

	public void setBeginInDate(Date beginInDate) {
		this.beginInDate = beginInDate;
	}
	
	public Date getEndInDate() {
		return endInDate;
	}

	public void setEndInDate(Date endInDate) {
		this.endInDate = endInDate;
	}
		
	public List<CaseOneToManyFirst> getCaseOneToManyFirstList() {
		return caseOneToManyFirstList;
	}

	public void setCaseOneToManyFirstList(List<CaseOneToManyFirst> caseOneToManyFirstList) {
		this.caseOneToManyFirstList = caseOneToManyFirstList;
	}
	public List<CaseOneToManySecond> getCaseOneToManySecondList() {
		return caseOneToManySecondList;
	}

	public void setCaseOneToManySecondList(List<CaseOneToManySecond> caseOneToManySecondList) {
		this.caseOneToManySecondList = caseOneToManySecondList;
	}
	public List<CaseOneToManyThird> getCaseOneToManyThirdList() {
		return caseOneToManyThirdList;
	}

	public void setCaseOneToManyThirdList(List<CaseOneToManyThird> caseOneToManyThirdList) {
		this.caseOneToManyThirdList = caseOneToManyThirdList;
	}
}

leesite-module/src/main/java/com/funtl/leesite/modules/cases/entity/CaseOneToManySecond.java
/*
 * Copyright 2015-2017 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.funtl.leesite.modules.cases.entity;

import org.hibernate.validator.constraints.Length;
import javax.validation.constraints.NotNull;

import com.funtl.leesite.common.persistence.DataEntity;
import com.funtl.leesite.common.utils.excel.annotation.ExcelField;

/**
 * 生成示例Entity
 * @author Lusifer
 * @version 2017-05-05
 */
public class CaseOneToManySecond extends DataEntity<CaseOneToManySecond> {
	
	private static final long serialVersionUID = 1L;
	private String startarea;		// 出发地
	private String endarea;		// 目的地
	private Double price;		// 代理价格
	private CaseOneToManyMain caseOneToManyMain;		// 外键 父类
	
	public CaseOneToManySecond() {
		super();
	}

	public CaseOneToManySecond(String id){
		super(id);
	}

	public CaseOneToManySecond(CaseOneToManyMain caseOneToManyMain){
		this.caseOneToManyMain = caseOneToManyMain;
	}

	@Length(min=1, max=64, message="出发地长度必须介于 1 和 64 之间")
	@ExcelField(title="出发地", align=2, sort=1)
	public String getStartarea() {
		return startarea;
	}

	public void setStartarea(String startarea) {
		this.startarea = startarea;
	}
	
	@Length(min=1, max=64, message="目的地长度必须介于 1 和 64 之间")
	@ExcelField(title="目的地", align=2, sort=2)
	public String getEndarea() {
		return endarea;
	}

	public void setEndarea(String endarea) {
		this.endarea = endarea;
	}
	
	@NotNull(message="代理价格不能为空")
	@ExcelField(title="代理价格", align=2, sort=3)
	public Double getPrice() {
		return price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}
	
	@Length(min=1, max=64, message="外键长度必须介于 1 和 64 之间")
	public CaseOneToManyMain getCaseOneToManyMain() {
		return caseOneToManyMain;
	}

	public void setCaseOneToManyMain(CaseOneToManyMain caseOneToManyMain) {
		this.caseOneToManyMain = caseOneToManyMain;
	}
	
}

leesite-module/src/main/java/com/funtl/leesite/modules/cases/entity/CaseTreeTable.java
/*
 * Copyright 2015-2017 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.funtl.leesite.modules.cases.entity;

import org.hibernate.validator.constraints.Length;
import javax.validation.constraints.NotNull;
import com.fasterxml.jackson.annotation.JsonBackReference;

import com.funtl.leesite.common.persistence.TreeEntity;

/**
 * 生成示例Entity
 * @author Lusifer
 * @version 2017-05-05
 */
public class CaseTreeTable extends TreeEntity<CaseTreeTable> {
	
	private static final long serialVersionUID = 1L;
	private String name;		// 名称
	private Integer sort;		// 排序
	private CaseTreeTable parent;		// 父级编号
	private String parentIds;		// 所有父级编号
	
	public CaseTreeTable() {
		super();
	}

	public CaseTreeTable(String id){
		super(id);
	}

	@Length(min=1, max=100, message="名称长度必须介于 1 和 100 之间")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@NotNull(message="排序不能为空")
	public Integer getSort() {
		return sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}
	
	@JsonBackReference
	@NotNull(message="父级编号不能为空")
	public CaseTreeTable getParent() {
		return parent;
	}

	public void setParent(CaseTreeTable parent) {
		this.parent = parent;
	}
	
	@Length(min=1, max=2000, message="所有父级编号长度必须介于 1 和 2000 之间")
	public String getParentIds() {
		return parentIds;
	}

	public void setParentIds(String parentIds) {
		this.parentIds = parentIds;
	}
	
	public String getParentId() {
		return parent != null && parent.getId() != null ? parent.getId() : "0";
	}
}

leesite-module/src/main/webapp/views/modules/sys/officeIndex.jsp
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="/views/include/taglib.jsp"%>

<!DOCTYPE html>
<!--[if IE 8]> <html lang="zh" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="zh" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html>
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <title>${fns:getConfig('productName')} | 机构管理</title>
    <meta name="decorator" content="default"/>
    <%@include file="/views/include/treeview.jsp" %>
</head>

<body class="page-container-bg-solid page-header-fixed page-sidebar-closed-hide-logo">
<!-- BEGIN CONTAINER -->
<div class="page-container">
    <!-- BEGIN SIDEBAR -->
    <div class="page-sidebar-wrapper">
        <!-- BEGIN SIDEBAR -->
        <div class="page-sidebar navbar-collapse collapse">
            <!-- BEGIN SIDEBAR MENU -->
            <ul class="page-sidebar-menu" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
                <li class="heading">
                    <h3 class="uppercase">功能菜单</h3>
                </li>
                <t:menu menu="${fns:getTopMenu()}" parentName="系统设置" currentName="机构管理"></t:menu>
            </ul>
            <!-- END SIDEBAR MENU -->
        </div>
        <!-- END SIDEBAR -->
    </div>
    <!-- END SIDEBAR -->
    <!-- BEGIN CONTENT -->
    <div class="page-content-wrapper">
        <!-- BEGIN CONTENT BODY -->
        <div class="page-content" style="padding-top: 0;">
            <div class="row">
                <div class="col-md-2">
                    <div class="portlet light">
                        <div class="portlet-title">
                            <div class="caption">
                                <span class="caption-subject bold font-grey-gallery uppercase"> 组织机构 </span>
                                <span class="caption-helper"></span>
                            </div>
                            <div class="tools">
                                <a href="javascript:;" onclick="window.location = '${ctx}/sys/office/'">
                                    <i class="fa fa-refresh"></i>
                                </a>
                            </div>
                        </div>
                        <div class="portlet-body">
                            <div id="ztree" class="ztree"></div>
                        </div>
                    </div>
                </div>

                <div class="col-md-10">
                    <div class="portlet light">
                        <div class="portlet-title">
                            <div class="caption">
                                <span class="caption-subject bold font-grey-gallery uppercase"> 机构列表 </span>
                                <span class="caption-helper"></span>
                            </div>
                            <div class="tools">
                                <a href="" class="fullscreen"> </a>
                            </div>
                        </div>
                        <div class="portlet-body">
                            <iframe id="officeContent" name="officeContent" src="${ctx}/sys/office/list?id=&parentIds=" width="100%" height="800px" frameborder="0" scrolling="no"></iframe>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END CONTENT BODY -->
    </div>
    <!-- END CONTENT -->
</div>
<!-- END CONTAINER -->

<%@include file="/views/include/foot.jsp" %>
<script type="text/javascript">
    var setting = {
        data: {simpleData: {enable: true, idKey: "id", pIdKey: "pId", rootPId: '0'}},
        callback: {
            onClick: function (event, treeId, treeNode) {
                var id = treeNode.pId == '0' ? '' : treeNode.pId;
                $('#officeContent').attr("src", "${ctx}/sys/office/list?id=" + id + "&parentIds=" + treeNode.pIds);
            }
        }
    };

    function refreshTree() {
        $.getJSON("${ctx}/sys/office/treeData", function (data) {
            $.fn.zTree.init($("#ztree"), setting, data).expandAll(true);
        });
    }
    refreshTree();
</script>
</body>
</html>

leesite-module/src/main/webapp/views/modules/sys/officeList.jsp
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="/views/include/taglib.jsp"%>

<!DOCTYPE html>
<!--[if IE 8]> <html lang="zh" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="zh" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html>
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <title>${fns:getConfig('productName')} | 机构列表</title>
    <meta name="decorator" content="blank"/>
    <%@include file="/views/include/treetable.jsp" %>
</head>

<body style="background: white;">
<sys:message content="${message}"/>

<div class="row">
    <div class="col-md-12">
        <div class="pull-left">
            <shiro:hasPermission name="sys:office:add">
                <table:addRow url="${ctx}/sys/office/form?parent.id=${office.id}" title="机构" width="900px" height="600px" target="officeContent"></table:addRow><!-- 增加按钮 -->
            </shiro:hasPermission>
            <button class="btn btn-default btn-sm" data-toggle="tooltip" data-placement="left" onclick="refresh()" title="刷新"><i class="fa fa-refresh"></i> 刷新</button>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="table-scrollable">
            <table id="treeTable" class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th>机构名称</th>
                    <th>归属区域</th>
                    <th>机构编码</th>
                    <th>机构类型</th>
                    <th>备注</th>
                    <shiro:hasPermission name="sys:office:edit">
                        <th>操作</th>
                    </shiro:hasPermission></tr>
                </thead>
                <tbody id="treeTableList"></tbody>
            </table>
            <script type="text/template" id="treeTableTpl">
                <tr id="{{row.id}}" pId="{{pid}}">
                    <td><a  href="#" onclick="openDialogView('查看机构', '${ctx}/sys/office/form?id={{row.id}}','900px', '600px')">{{row.name}}</a></td>
                    <td>{{row.area.name}}</td>
                    <td>{{row.code}}</td>
                    <td>{{dict.type}}</td>
                    <td>{{row.remarks}}</td>
                    <td>
                        <shiro:hasPermission name="sys:office:view">
                            <a href="#" onclick="openDialogView('查看机构', '${ctx}/sys/office/form?id={{row.id}}','900px', '600px')" class="btn btn-info btn-xs" ><i class="fa fa-search-plus"></i> 查看</a>
                        </shiro:hasPermission>
                        <shiro:hasPermission name="sys:office:edit">
                            <a href="#" onclick="openDialog('修改机构', '${ctx}/sys/office/form?id={{row.id}}','900px', '600px', 'officeContent')" class="btn btn-success btn-xs" ><i class="fa fa-edit"></i> 修改</a>
                        </shiro:hasPermission>
                        <shiro:hasPermission name="sys:office:del">
                            <a href="${ctx}/sys/office/delete?id={{row.id}}" onclick="return confirmx('要删除该机构及所有子机构项吗？', this.href)" class="btn btn-danger btn-xs"><i class="fa fa-trash"></i> 删除</a>
                        </shiro:hasPermission>
                        <shiro:hasPermission name="sys:office:add">
                            <a href="#" onclick="openDialog('添加下级机构', '${ctx}/sys/office/form?parent.id={{row.id}}','900px', '600px', 'officeContent')" class="btn btn-primary btn-xs"><i class="fa fa-plus"></i> 添加下级机构</a>
                        </shiro:hasPermission>
                    </td>
                </tr>
            </script>
        </div>
    </div>
</div>

<%@include file="/views/include/foot.jsp" %>
<script type="text/javascript">
    $(document).ready(function() {
        var tpl = $("#treeTableTpl").html().replace(/(\/\/\<!\-\-)|(\/\/\-\->)/g,"");
        var data = ${fns:toJson(list)}, rootId = "${not empty office.id ? office.id : '0'}";
        addRow("#treeTableList", tpl, data, rootId, true);
        $("#treeTable").treeTable({expandLevel : 5});
    });

    function addRow(list, tpl, data, pid, root){
        for (var i=0; i<data.length; i++){
            var row = data[i];
            if ((${fns:jsGetVal('row.parentId')}) == pid){
                $(list).append(Mustache.render(tpl, {
                    dict: {
                        type: getDictLabel(${fns:toJson(fns:getDictList('sys_office_type'))}, row.type)
                    }, pid: (root?0:pid), row: row
                }));
                addRow(list, tpl, data, row.id);
            }
        }
    }

    function refresh(){//刷新或者排序，页码不清零
        window.location="${ctx}/sys/office/list";
    }
</script>
</body>
</html>